### ISSUE TITLE
"Critical error" when launching free trial

### ISSUE THREAD

**Issue by denho** [Automattic/wc-calypso-bridge#1121]
### Describe the bug

On WooCommerce.com, I clicked "Try for free", and after some time waiting for the site to be initialized, landed on this page with error:
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/2803994/236163111-1dba994e-afb5-4dff-ac45-a507a0e8d9b0.png">
After refreshing the page, the error has gone.

### Steps to reproduce

1. Click "Try for free" during WooCommerce.com onboarding.
2. Wait some time while the site is initialized.
3. See the error.

### WordPress Environment

-

### What plan is active?

Free trial

**Comment by mlaetitia** [comment]
Just encountererd the same issue yesterday twice: the first when creating the site and the second (second site) when accessing the Marketplace tab .

This is the error I had in creation (CLI):


```
[23-May-2023 12:53:31 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function add_settings_field() in /wordpress/plugins/woocommerce-brands/1.6.49/includes/class-wc-brands-admin.php:539
Stack trace:
#0 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): WC_Brands_Admin->add_brand_base_setting(Object(WP_Screen))
#1 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/6.2.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /wordpress/core/6.2.2/wp-admin/includes/class-wp-screen.php(424): do_action('current_screen', Object(WP_Screen))
#4 /wordpress/core/6.2.2/wp-admin/includes/screen.php(243): WP_Screen->set_current_screen()
#5 /wordpress/plugins/jetpack/12.2-a.9/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(505): set_current_screen('sync')
#6 /wordpress/plugins/jetpack/12.2-a.9/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(687): Automattic\Jetpack\Sync\Sender->get_items_to_send(Array, true)
#7 /wordpress/plugins/jetpack/12.2-a.9/jetpack_vendor/automattic/jetpack-sync/src/modules/class-module.php(373): Automattic\Jetpack\Sync\Sender->send_action('jetpack_full_sy...', Array)
#8 /wordpress/plugins/jetpack/12.2-a.9/jetpack_vendor/automattic/jetpack-sync/src/modules/class-constants.php(149): Automattic\Jetpack\Sync\Modules\Module->send_action('jetpack_full_sy...', Array)
#9 /wordpress/plugins/jetpack/12.2-a.9/jetpack_vendor/automattic/jetpack-sync/src/modules/class-full-sync-immediately.php(386): Automattic\Jetpack\Sync\Modules\Constants->send_full_sync_actions(true, Array, 1684846420.9025)
#10 /wordpress/plugins/jetpack/12.2-a.9/jetpack_vendor/automattic/jetpack-sync/src/modules/class-full-sync-immediately.php(364): Automattic\Jetpack\Sync\Modules\Full_Sync_Immediately->send()
#11 /wordpress/plugins/jetpack/12.2-a.9/jetpack_vendor/automattic/jetpack-sync/src/modules/class-full-sync-immediately.php(330): Automattic\Jetpack\Sync\Modules\Full_Sync_Immediately->continue_sending()
#12 /wordpress/plugins/jetpack/12.2-a.9/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(327): Automattic\Jetpack\Sync\Modules\Full_Sync_Immediately->continue_enqueuing()
#13 /wordpress/plugins/jetpack/12.2-a.9/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(296): Automattic\Jetpack\Sync\Sender->continue_full_sync_enqueue()
#14 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): Automattic\Jetpack\Sync\Sender->do_full_sync('')
#15 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(Object(WP_Error), Array)
#16 /wordpress/core/6.2.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#17 /wordpress/core/6.2.2/wp-includes/load.php(1144): do_action('shutdown')
#18 [internal function]: shutdown_action_hook()
#19 {main}
  thrown in /wordpress/plugins/woocommerce-brands/1.6.49/includes/class-wc-brands-admin.php on line 539
```

**Comment by PanosSynetos** [comment]
To close the circle, it's not Brands related. Brands is calling `add_settings_field` just like WooCommerce does, so if Brands was not around, WooCommerce would have thrown this error.

I suspect is due to Jetpack, by reading the stack trace - I'll ping someone from Jetpack to have a look

**Comment by PanosSynetos** [comment]
This error is not due to Jetpack - We investigated (thanks @fgiannar ) and it's due to this check

https://github.com/woocommerce/woocommerce-brands/blob/1c1d92825f867109787e28d76284b6dadd0361d1/includes/class-wc-brands-admin.php#L535-L537

```php
	public function add_brand_base_setting() {
		if ( ! $screen = get_current_screen() || 'options-permalink' !== $screen->id ) {
			return;
		}

```

The assignment inside the if statement is misleading; the above code does not do early exits properly, and runs on every page

I will recommend to the responsible team to change it to and release a fix the soonest

```php
	$screen = get_current_screen();
	if ( ! $screen || 'options-permalink' !== $screen->id ) {
		return;
	}
```

**Comment by warrendholmes** [comment]
@PanosSynetos We can close this one out now right?

**Comment by PanosSynetos** [comment]
Ventures released a version of Brands, fixing this issue https://github.com/woocommerce/woocommerce-brands/pull/282

Closing this and marking it as done
